
[[checksum_functions]]
== Cryptographic Hash Functions

The CHECKSUM value is calculated by a chosen cryptographic hash function
specified in the HASHA property parameter. Certain hash functions accept
customization specifiers, which can be specified in the HASHP property
parameter.


=== Supported Hash Functions

CHECKSUM supports the following hash algorithms.

[[supported_table]]
==== Hash Function Specifiers

CHECKSUM supported hash algorithms are listed in the following table.

* The CHECKSUM value contains the output of the hash function, which
  is usually stored in hexadecimal format as the `text` value type.
* The identifier from this table should be put as value of the property
  parameter HASHA.
* Algorithms with a "Variable" message digest size mean its length can
  be specified by a HASHP specifier.

Algorithms with no specifiers:

|===
| Algorithm | Identifier | Message Digest Size (bits) | Description

| SHA-2 SHA-224 | sha224 | 224 | <<RFC6234>>; <<NIST-FIPS-180-4>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 8 (SHA-224)
| SHA-2 SHA-256 | sha256 | 256 | <<RFC6234>>; <<NIST-FIPS-180-4>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 4 (SHA-256)
| SHA-2 SHA-384 | sha384 | 384 | <<RFC6234>>; <<NIST-FIPS-180-4>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 6 (SHA-384)
| SHA-2 SHA-512 | sha512 | 512 | <<RFC6234>>; <<NIST-FIPS-180-4>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 5 (SHA-512)
| SHA-2 SHA-512/224 | sha512-224 | 224 | <<NIST-FIPS-180-4>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 9 (SHA-512/224)
| SHA-2 SHA-512/256 | sha512-256 | 256 | <<NIST-FIPS-180-4>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 10 (SHA-512/256)
| WHIRLPOOL | whirlpool | 512 | <<WHIRLPOOL>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 7 (WHIRLPOOL)
| STREEBOG-256 | streebog256 | 256 | <<STREEBOG>> GOST R 34.11-2012; <<RFC6986>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 12 (STREEBOG-256)
| STREEBOG-512 | streebog512 | 512 | <<STREEBOG>> GOST R 34.11-2012; <<RFC6986>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 11 (STREEBOG-512)
| SHA3-224 | sha3-224 | 224 | <<NIST-FIPS-202>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 13 (SHA3-224)
| SHA3-256 | sha3-256 | 256 | <<NIST-FIPS-202>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 14 (SHA3-256)
| SHA3-384 | sha3-384 | 384 | <<NIST-FIPS-202>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 15 (SHA3-384)
| SHA3-512 | sha3-512 | 512 | <<NIST-FIPS-202>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 16 (SHA3-512)
| SM3 | sm3 | 512 | <<?I-D.shen-sm3-hash>>; <<SM3>>; <<ISO-IEC-10118-3>> Dedicated Hash-Function 17 (SM3)
| IANA registered hash algorithm | iana-token | iana-token | IANA
| Vendor-specific hash algorithm | x-token | Vendor specific | Vendor specific

|===

Algorithms with specifiers:

|===
| Algorithm | Identifier | Message Digest Size (bits) | Specifier(s) | Description

| SHAKE-128 | shake128 | Varys | L: integer (default: 256) | <<NIST-FIPS-202>>
| SHAKE-256 | shake256 | Varys | L: integer (default: 512) | <<NIST-FIPS-202>>
| cSHAKE-128 | cshake128 | Varys | L: integer (default: 256), N: text (default: ""), S: text (default: "") | <<NIST-SP-800-185>>
| cSHAKE-256 | cshake256 | Varys | L: integer (default: 512), N: text (default: ""), S: text  (default: "")| <<NIST-SP-800-185>>
| ParallelHash-128 | parallel128 | Varys | B: integer (default: 64), L: integer (default: 256), S: text (default: "") | <<NIST-SP-800-185>>
| ParallelHash-256 | parallel256 | Varys | B: integer (default: 64), L: integer (default: 256), S: text (default: "") | <<NIST-SP-800-185>>
| IANA registered hash algorithm | iana-token | iana-token | iana-token | IANA
| Vendor-specific hash algorithm | x-token | Vendor specific | Vendor specific | Vendor specific

|===

===== Example

[source]
----
sha3-256('BEGIN:VCARD') = "f1fcbc9bddcd44b1e50db99a277bc868" +
                          "61736eb32cb30ef7e7a2c9ef95c05d50"
----

The default algorithm is `sha3-256`.  An implementation that
supports this document *MUST* support at least the `sha3-256`
function.



[[checksum_sha2]]
==== The SHA-2 Hash Functions

Secure Hash Algorithm 2 (SHA-2) is a family of secure hash algorithms
defined in <<NIST-FIPS-180-4>>: SHA-224, SHA-256, SHA-384, SHA-512,
SHA-512/224 and SHA-512/256.

* SHA-256 and SHA-512 are the two core hash functions that differ by
  process parameters, which produce a hash value of 256 and 512 bits
  respectively.
* SHA-224 is identical to SHA-256, except that different initial hash
  values are used, and the final hash value is truncated to 224 bits.
* SHA-384, SHA-512/224, SHA-512/256 are identical to SHA-512, except
  that different initial hash values are used, and the final hash value is
  truncated to 384, 224, 256 bits respectively. In particular,
  SHA-512/224 and SHA-512/256 use initial hash values generated by the
  "`SHA-512/t IV Generation Function`" given in <<NIST-FIPS-180-4>>.


[[checksum_whirlpool]]
==== The WHIRLPOOL Hash Function

WHIRLPOOL is a hash function that operates on messages less than 2^256
bits in length, and produces a hash value of 512 bits <<WHIRLPOOL>>.

It uses Merkle-Damgard strengthening and the Miyaguchi-Preneel hashing
scheme with a dedicated 512-bit block cipher called "W" <<WHIRLPOOL>>.


[[checksum_sm3]]
==== The SM3 Hash Function

SM3 is a hash function <<?I-D.shen-sm3-hash>> standardized by the Chinese
Commercial Cryptography Administration Office <<SM3>> for the use of
electronic authentication service systems.

SM3 is an iterated hash function based on a Merkle-Damgard design,
processes on 512-bit input message blocks with a 256-bit state, and
produces a 256-bit hash value.


[[checksum_sha3]]
==== The SHA-3 Hash Functions

Secure Hash Algorithm-3 (SHA-3) is a family of hash functions defined in
<<NIST-FIPS-202>> consisting of:

* four cryptographic hash functions, SHA3-224, SHA3-256, SHA3-384,
  SHA3-512; and
* two extendable-output functions (XOFs), SHAKE128 and SHAKE256.

Each SHA-3 function is based on an instance of the KECCAK algorithm
<<KECCAK>> which won the SHA-3 Cryptographic Hash Algorithm Competition
<<NIST-FIPS-202>>.

* SHA3-224, SHA3-256, SHA3-384, SHA3-512 produce a hash value output
  of 224, 256, 384 and 512 bits respectively.
* SHAKE128 and SHAKE256 are XOFs that produce output of arbitrary
  length, which can be specified using the "HASHP" property parameter.


Notes concerning SHA-3 based XOFs <<NIST-FIPS-202>>:

* Output of a XOF can be considered as an infinite string, and the
  "HASHP" property parameter simply determines how many initial bits of
  the initial string to use.
* The SHAKE-256 and -128 functions, as long as at least 2x bits of their
  output is used, they have generic security strengths of 256 and 128
  bits. However, using an excess of 64 or 32 bytes of their output
  respectively, does not increase their collision-resistance.


[[checksum_streebog]]
==== The STREEBOG Hash Functions

Streebog (or Stribog) is a family of two separate hash functions defined
in the Russian standard GOST R 34.11-2012 <<STREEBOG>> where the
functions differ in their output lengths, which are 256- and 512-bits
respectively.

Streebog accepts message block sizes of 512-bits, and both functions
only differ in the different IVs used other than the output length
<<STREEBOG>>.


[[checksum_blake2]]
==== The BLAKE2 Hash Functions

BLAKE2, described in <<BLAKE2>> and <<RFC7693>>, is a hash algorithm
that comes in two flavors, BLAKE2b and BLAKE2s. It is the successor of
BLAKE <<BLAKE>> which was a NIST SHA-3 competition finalist.

* BLAKE2b is optimized for 64-bit platforms and produces hash values of
  any size between 1 and 64 bytes
* BLAKE2s is optimized for 8- to 32-bit platforms and produces hash
  values of any size between 1 and 32 bytes

While BLAKE2 allows customizing parameters, including salt and a
customization string, implementations that adhere to this specification
should adopt BLAKE2 as defined in <<RFC7693>>.


[[checksum_sha3_ext]]
==== The SHA-3 Extension Hash Functions

<<NIST-SP-800-185>> defines a number of additional hash algorithms based
on algorithms defined in <<NIST-FIPS-202>>, including:

* cSHAKE-128, cSHAKE-256: customizable SHAKE functions, which take extra
  inputs of hash value length, a function name string, and a customization
  string;
* ParallelHash128, ParallelHash256: supports efficient hashing of very
  long strings by taking advantage of the parallelism available in modern
  processors based on SHAKE. These take the extra inputs of block size,
  hash value length and a customization string.

Both cSHAKE and ParallelHash are XOFs that can produce variable length
output. The number suffix at their names mean the security strength bits
of the algorithm.


// TODO in the future ## BLAKE2X


=== Selection Considerations

==== Collision Resistance of Hash Function Families

For our purposes we specify the following strength families of hash
algorithms. Hash functions placed in the higher bracket are considered
"more resistant" in algorithm selection.

|===
| Strength | Hash Function Identifier

| 1 | sha224, sha256, sha384, sha512, sha512-224, sha512-256
| 2 | whirlpool, streebog256, streebog512
| 3 | blake2b256, blake2b384, blake2b512, blake2s224, blake2s256, sm3,
shake128, shake256, sha3-224, sha3-256, sha3-384, sha3-512

|===

==== Guidelines for Hash Function Selection

* Collision-resistance: higher bit length digests are generally
  preferable to lower bit length digests due to lower susceptibility to
  collisions.
* Performance: some hash functions are more computation intensive.
  Higher bit length digests generally require more computation to
  generate.
* History: a hash algorithm that has withstood cryptanalytic attacks
  provide better confidence than ones that have not been in widespread
  use.
* Availability and interoperability: certain hash algorithms, such as
  SHA-2 (<<RFC6234>>; <<NIST-FIPS-180-4>>; <<ISO-IEC-10118-3>> Dedicated
  Hash-Function 4 (SHA-256)), are more prevalently available on
  computing platforms.

Selection of the hash function should be based on a balance of
collision resistance, performance, history and interoperability.


==== Hash Functions Considered Unsuitable

The following hash functions are specifically excluded due to stated
reasons:

* RIPEMD-160 <<ISO-IEC-10118-3>> Dedicated Hash-Function 1 and
  RIPEMD-128 <<ISO-IEC-10118-3>> Dedicated Hash-Function 2,
  are specifically excluded as they do no longer provide a sufficient
  level of collision resistance, see <<ISO-IEC-10118-3,7.1>> Note
  2 <<ISO-IEC-10118-3,8>> Note 2. The RIPEMD optional
  extensions RIPEMD-256 and RIPEMD-320 <<RIPEMD160>> are also excluded as
  they are of the same security levels as RIPEMD-128 and RIPE-160
  respectively.

* SHA-1 <<RFC3174>> <<ISO-IEC-10118-3>> Dedicated Hash-Function 3 is
  excluded as it does not provide a sufficient level of collision
  resistance, see <<ISO-IEC-10118-3,9.1>> Note 2.

* CRC-32 <<ISO-IEC-13239>> and in general CRC algorithms are excluded due
  to weak collision resistance.


////
Integrity calculation methods should not include other integrity
calculation methods inside.
////
