
[[symbols]]
== Symbols And Abbreviations

=== Functions

These functions are *REQUIRED* and *MUST* be implemented
for compliance to this document.

==== SORT

Sorts an list according to alphabetical order (A-Z).

==== LIST-TO-TEXT

This function returns a Unicode string (<<RFC8259,7>>)
containing a string representation of a list of string values, each
followed by a selected delimiter character.

[source]
----
LIST-TO-TEXT(list, delimiter) =
  value(list, 1) + delimiter +
  value(list, 2) + delimiter +
  ...
  value(list, last-element-position(list))
----

where:
* `+` indicates concatenation;
* `value(l, i)` is the i-th value in the list `l` in string representation;
* `last-element-position(a)` returns the last element position of list
  `l`.


==== PREPHASH-PROPERTY-PARAMETER-KEY

This function returns a Unicode string (<<RFC8259,7>>)
representation of the normalized property parameter key.

[source]
----
PREPHASH-PROPERTY-PARAMETER-KEY(parameter) = normalize(key(parameter))
----

where:
* `+` indicates concatenation;
* `key(parameter)` is the property parameter key;
* `normalize(s)` is a function that normalizes the key s.



==== PREPHASH-PROPERTY-PARAMETER-VALUES

This function returns a Unicode string (<<RFC8259,7>>)
representation of the normalized property parameter values.

[source]
----
PREPHASH-PROPERTY-PARAMETER-VALUES(parameter) =
  LIST-TO-TEXT(
    SORT(
      values(parameter, 1),
      values(parameter, 2),
      ...
    ),
    ";"
  )
----

where:
* `+` indicates concatenation;
* `values(parameter, i)` is the i-th property parameter value in
  `parameter`.


==== PREPHASH-PROPERTY-PARAMETER

Converts a property parameter into a string, with its key and values.

This function returns a Unicode string (<<RFC8259,7>>)
containing a sequence of zero or more list values in string format,
each followed by a ';' character.

[source]
----
PREPHASH-PROPERTY-PARAMETER(parameter) =
  "{" +
    PREPHASH-PROPERTY-PARAMETER-KEY(property) + ":" +
    PREPHASH-PROPERTY-PARAMETER-VALUES(property) +
  "}"
----

where:
* + indicates concatenation.


==== PREPHASH-PROPERTY-PARAMETERS

This function returns a Unicode string (<<RFC8259,7>>)
representation of a set of property parameters.

We exclude the `VALUE` property parameter in this calculation (such as
`VALUE=TEXT`) as this information is represented in
PREPHASH-PROPERTY-VALUE-HASHA.

[source]
----
PREPHASH-PROPERTY-PARAMETERS(property) =
  "#" +
  LIST-TO-TEXT(
    SORT([
      PREPHASH-PROPERTY-PARAMETER(parameter(property, 1)),
      PREPHASH-PROPERTY-PARAMETER(parameter(property, 2)),
      ...
    ]),
    ";"
  )
----

where:
* + indicates concatenation;
* parameters(property, i) is the i-th parameter of `property`.


==== PREPHASH-PROPERTY-KEY

This function returns a Unicode string (<<RFC8259,7>>)
representation of the normalized property key.

[source]
----
PREPHASH-PROPERTY-KEY(property) = normalize(key(property))
----

where:
* + indicates concatenation;
* key(property) is the property key;
* normalize(s) is a function that normalizes the key s.


==== PREPHASH-PROPERTY-VALUE-HASHA

This function returns a Unicode string (<<RFC8259,7>>)
representation of the normalized property value type. Since the property
value type is represented here, we exclude the `VALUE` property
parameter in PREPHASH-PROPERTY-PARAMETERS (such as `VALUE=TEXT`)

[source]
----
PREPHASH-PROPERTY-VALUE-HASHA(property) = UPCASE(type(property))
----

where:
* + indicates concatenation;
* type(property) is the property value type, if not explicitly provided,
  it should be filled in according to <<RFC6350>>;
* normalize(s) is a function that normalizes the property value type s.


==== PREPHASH-PROPERTY-VALUES

This function returns a Unicode string (<<RFC8259,7>>)
representation of the normalized property values.

Certain content types allow storing multiple values (as a list) in the
same property line. For example, in the ADR and N properties, values are
separated by the ";" delimiter, while in NICKNAME and CATEGORIES they
are separated by the "," delimiter <<RFC6350,3.3>>.

[source]
----
PREPHASH-PROPERTY-VALUES(property) =
  LIST-TO-TEXT(
    SORT(
      values(property, 1),
      values(property, 2),
      ...
    ),
    ";"
  )
----

where:
* + indicates concatenation;
* values(property, i) is the i-th property value in `property`.


==== PREPHASH-PROPERTY

This function returns a Unicode string (<<RFC8259,7>>)
representation of a single property.

[source]
----
PREPHASH-PROPERTY(property) =
  PREPHASH-PROPERTY-KEY(property) + ":" +
  PREPHASH-PROPERTY-VALUE-HASHA(property) + "/" +
  PREPHASH-PROPERTY-VALUES(property) + "?" +
  PREPHASH-PROPERTY-PARAMETERS(property)
----

where:
* + indicates concatenation


==== HASH-PROPERTY

This function returns a Unicode string (<<RFC8259,7>>)
representation of a single property.

[source]
----
HASH-PROPERTY-TO-TEXT(property) =
  PREPHASH-PROPERTY-KEY(property) + ":" +
  HASH(PREPHASH-PROPERTY(property)
----

where:
* + indicates concatenation


==== HASH-AND-PREPHASH-PROPERTIES

This function returns a Unicode string (<<RFC8259,7>>)
representation of a set of properties.

[source]
----
HASH-AND-PREPHASH-PROPERTIES(properties) =
  LIST-TO-TEXT(
    SORT([
      HASH-PROPERTY(property(properties, 1)),
      HASH-PROPERTY(property(properties, 2)),
      ...
    ]),
    CRLF
  )
----

where:
* + indicates concatenation;
* property(properties, i) is the i-th property of `properties`;
* HASH(s) is selected cryptographic hash function applied to string `s`.


==== PREPHASH-COMPONENT-NAME

This function returns a Unicode string (<<RFC8259,7>>)
representation of the normalized vObject name.

[source]
----
PREPHASH-COMPONENT-NAME(component) = normalize(name(component))
----

where:
* name(c) is the component name of component `c`.


==== PREPHASH-COMPONENT

This function returns a Unicode string (<<RFC8259,7>>)
representation of a vObject. The similarity of this representation
with the vObject structure is intentional for readability purposes.

[source]
----
PREPHASH-COMPONENT(component) =
  "BEGIN:" + PREPHASH-COMPONENT-NAME(component) + ":CHECKSUM" + CRLF +
    HASH-AND-PREPHASH-PROPERTIES(properties(component)) + CRLF +
  "END:" + PREPHASH-COMPONENT-NAME(component) + ":CHECKSUM"
----

where:
* + indicates concatenation;
* properties(c) returns the properties of the component `c` in an list;


==== HASH-COMPONENT

This function returns a Unicode string (<<RFC8259,7>>) as the
output of a selected cryptographic hash function applied on a
vObject.

[source]
----
HASH-COMPONENT(component) = HASH(PREPHASH-COMPONENT(component))
----

==== HASH

This function returns the calculated hash of an input string and outputs
the hash in string representation.

[source]
----
HASH(string) = generate-hash-function(
                 selected-hash-function,
                 selected-hash-parameters
               )(string)
----

where:
* `generate-hash-function(a, p)` creates a new cryptographic hash function
  that uses the hash algorithm `a` with algorithm parameters `p` which
  takes a string input and generates the hash using a string output;
* `selected-hash-function` is the selected cryptographic hash algorithm
  selected by the user (and/or CUA);
* `selected-hash-parameters` are the selected parameters for the
  selected cryptographic hash function by the user (and/or CUA), and
  could be different per algorithm.


